import React, { createContext, useEffect, useMemo, useState } from 'react';

export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'as', label: 'অসমীয়া (Assamese)' },
  { code: 'bn', label: 'বাংলা (Bengali)' },
  { code: 'brx', label: 'बड़ो (Bodo)' },
  { code: 'doi', label: 'डोगरी (Dogri)' },
  { code: 'gu', label: 'ગુજરાતી (Gujarati)' },
  { code: 'hi', label: 'हिन्दी (Hindi)' },
  { code: 'kn', label: 'ಕನ್ನಡ (Kannada)' },
  { code: 'ks', label: 'کٲشُر (Kashmiri)' },
  { code: 'kok', label: 'कोंकणी (Konkani)' },
  { code: 'mai', label: 'मैथिली (Maithili)' },
  { code: 'ml', label: 'മലയാളം (Malayalam)' },
  { code: 'mni', label: 'ꯃꯤꯇꯩꯂꯣꯟ (Manipuri)' },
  { code: 'mr', label: 'मराठी (Marathi)' },
  { code: 'ne', label: 'नेपाली (Nepali)' },
  { code: 'or', label: 'ଓଡ଼ିଆ (Odia)' },
  { code: 'pa', label: 'ਪੰਜਾਬੀ (Punjabi)' },
  { code: 'sa', label: 'संस्कृतम् (Sanskrit)' },
  { code: 'sat', label: 'ᱥᱟᱱᱛᱟᱲᱤ (Santali)' },
  { code: 'sd', label: 'سنڌي (Sindhi)' },
  { code: 'ta', label: 'தமிழ் (Tamil)' },
  { code: 'te', label: 'తెలుగు (Telugu)' },
  { code: 'ur', label: 'اردو (Urdu)' },
  { code: 'es', label: 'Español (Spanish)' },
];

const translations = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.symptoms': 'Symptom Checker',
    'nav.doctors': 'Doctors',
    'nav.emergency': 'Emergency',
    'nav.healthTips': 'Health Tips',
    'nav.reports': 'Reports',
    'nav.myService': 'My Service',
    'nav.doctorDirectory': 'Doctor Directory',
    'nav.logout': 'Logout',
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your personal and medical information',
    'profile.edit': 'Edit Mode',
    'profile.save': 'Save Changes',
    'profile.saving': 'Saving...',
    'profile.info': 'Profile Info',
    'profile.history': 'History',
    'profile.language': 'Language',
    'profile.languageHelp': 'Choose the language used across the app.',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone Number',
    'profile.age': 'Age',
    'profile.gender': 'Gender',
    'profile.bloodGroup': 'Blood Group',
    'profile.emergencyContact': 'Emergency Contact',
    'profile.occupation': 'Occupation',
    'profile.address': 'Address',
    'profile.specialty': 'Specialty',
    'profile.experience': 'Experience',
    'profile.fee': 'Consultation Fee',
    'profile.clinicPhone': 'Clinic Phone',
    'profile.location': 'Location',
    'profile.availability': 'Availability',
    'profile.patientProfile': 'Patient Profile',
    'profile.doctorProfile': 'Doctor Profile',
    'profile.previousDiseases': 'Previous Diseases',
    'profile.currentDisease': 'Current Disease or Concern',
    'profile.heartRate': 'Previous 7 Day Heart Rate',
    'profile.bp': 'Blood Pressure Log',
    'profile.medicines': 'Medicines You Take',
    'profile.allergies': 'Allergies',
    'profile.saveHistory': 'Save History',
    'symptoms.badge': 'AI Symptom Checker',
    'symptoms.title': 'Describe or Select Symptoms',
    'symptoms.subtitle': 'Choose common symptoms, write a sentence in your own words, or combine both for a richer AI analysis.',
    'symptoms.analyze': 'Analyze Symptoms',
    'symptoms.analyzing': 'Analyzing with AI...',
    'symptoms.clear': 'Clear',
    'reports.badge': 'Medical Report Analyzer',
    'reports.title': 'Analyze Reports',
    'reports.subtitle': 'Upload a prescription, lab report, or scan image. The analysis is summarized in one paragraph and organized into useful medical data points.',
    'reports.upload': 'Upload report photo or PDF',
    'reports.analyze': 'Analyze Report',
    'reports.analyzing': 'Analyzing...',
    'reports.savedReports': 'Saved Reports',
  },
  hi: {
    'nav.dashboard': 'डैशबोर्ड',
    'nav.symptoms': 'लक्षण जांच',
    'nav.doctors': 'डॉक्टर',
    'nav.emergency': 'आपातकाल',
    'nav.healthTips': 'स्वास्थ्य सुझाव',
    'nav.reports': 'रिपोर्ट',
    'nav.myService': 'मेरी सेवा',
    'nav.doctorDirectory': 'डॉक्टर सूची',
    'nav.logout': 'लॉग आउट',
    'profile.title': 'मेरी प्रोफाइल',
    'profile.subtitle': 'अपनी व्यक्तिगत और चिकित्सा जानकारी प्रबंधित करें',
    'profile.edit': 'संपादित करें',
    'profile.save': 'बदलाव सेव करें',
    'profile.saving': 'सेव हो रहा है...',
    'profile.info': 'प्रोफाइल जानकारी',
    'profile.history': 'इतिहास',
    'profile.language': 'भाषा',
    'profile.languageHelp': 'ऐप में उपयोग की जाने वाली भाषा चुनें।',
    'profile.fullName': 'पूरा नाम',
    'profile.email': 'ईमेल',
    'profile.phone': 'फोन नंबर',
    'profile.age': 'उम्र',
    'profile.gender': 'लिंग',
    'profile.bloodGroup': 'ब्लड ग्रुप',
    'profile.emergencyContact': 'आपातकालीन संपर्क',
    'profile.occupation': 'पेशा',
    'profile.address': 'पता',
    'profile.specialty': 'विशेषज्ञता',
    'profile.experience': 'अनुभव',
    'profile.fee': 'परामर्श शुल्क',
    'profile.clinicPhone': 'क्लिनिक फोन',
    'profile.location': 'स्थान',
    'profile.availability': 'उपलब्धता',
    'profile.patientProfile': 'मरीज प्रोफाइल',
    'profile.doctorProfile': 'डॉक्टर प्रोफाइल',
    'profile.previousDiseases': 'पिछली बीमारियां',
    'profile.currentDisease': 'वर्तमान बीमारी या समस्या',
    'profile.heartRate': 'पिछले 7 दिन की हार्ट रेट',
    'profile.bp': 'ब्लड प्रेशर लॉग',
    'profile.medicines': 'आप जो दवाएं लेते हैं',
    'profile.allergies': 'एलर्जी',
    'profile.saveHistory': 'इतिहास सेव करें',
    'symptoms.badge': 'AI लक्षण जांच',
    'symptoms.title': 'लक्षण लिखें या चुनें',
    'symptoms.subtitle': 'सामान्य लक्षण चुनें, अपने शब्दों में लिखें, या बेहतर AI विश्लेषण के लिए दोनों करें।',
    'symptoms.analyze': 'लक्षण विश्लेषण करें',
    'symptoms.analyzing': 'AI विश्लेषण कर रहा है...',
    'symptoms.clear': 'साफ करें',
    'reports.badge': 'मेडिकल रिपोर्ट विश्लेषक',
    'reports.title': 'रिपोर्ट विश्लेषण',
    'reports.subtitle': 'प्रिस्क्रिप्शन, लैब रिपोर्ट या स्कैन इमेज अपलोड करें। विश्लेषण एक पैराग्राफ और उपयोगी डेटा पॉइंट्स में दिखेगा।',
    'reports.upload': 'रिपोर्ट फोटो या PDF अपलोड करें',
    'reports.analyze': 'रिपोर्ट विश्लेषण करें',
    'reports.analyzing': 'विश्लेषण हो रहा है...',
    'reports.savedReports': 'सेव रिपोर्ट',
  },
  es: {
    'nav.dashboard': 'Panel',
    'nav.symptoms': 'Síntomas',
    'nav.doctors': 'Doctores',
    'nav.emergency': 'Emergencia',
    'nav.healthTips': 'Consejos',
    'nav.reports': 'Informes',
    'nav.myService': 'Mi servicio',
    'nav.doctorDirectory': 'Directorio médico',
    'nav.logout': 'Salir',
    'profile.title': 'Mi Perfil',
    'profile.subtitle': 'Gestiona tu información personal y médica',
    'profile.edit': 'Editar',
    'profile.save': 'Guardar cambios',
    'profile.saving': 'Guardando...',
    'profile.info': 'Información',
    'profile.history': 'Historial',
    'profile.language': 'Idioma',
    'profile.languageHelp': 'Elige el idioma usado en la app.',
    'profile.fullName': 'Nombre completo',
    'profile.email': 'Correo',
    'profile.phone': 'Teléfono',
    'profile.age': 'Edad',
    'profile.gender': 'Género',
    'profile.bloodGroup': 'Grupo sanguíneo',
    'profile.emergencyContact': 'Contacto de emergencia',
    'profile.occupation': 'Ocupación',
    'profile.address': 'Dirección',
    'profile.specialty': 'Especialidad',
    'profile.experience': 'Experiencia',
    'profile.fee': 'Tarifa de consulta',
    'profile.clinicPhone': 'Teléfono clínica',
    'profile.location': 'Ubicación',
    'profile.availability': 'Disponibilidad',
    'profile.patientProfile': 'Perfil de paciente',
    'profile.doctorProfile': 'Perfil de doctor',
    'profile.previousDiseases': 'Enfermedades previas',
    'profile.currentDisease': 'Enfermedad o inquietud actual',
    'profile.heartRate': 'Ritmo cardíaco de 7 días',
    'profile.bp': 'Registro de presión arterial',
    'profile.medicines': 'Medicamentos que tomas',
    'profile.allergies': 'Alergias',
    'profile.saveHistory': 'Guardar historial',
    'symptoms.badge': 'Verificador de síntomas AI',
    'symptoms.title': 'Describe o Selecciona Síntomas',
    'symptoms.subtitle': 'Elige síntomas comunes, escribe una frase, o combina ambos para un mejor análisis.',
    'symptoms.analyze': 'Analizar síntomas',
    'symptoms.analyzing': 'Analizando con AI...',
    'symptoms.clear': 'Limpiar',
    'reports.badge': 'Analizador de informes médicos',
    'reports.title': 'Analizar Informes',
    'reports.subtitle': 'Sube una receta, informe de laboratorio o imagen. El análisis se resume y organiza en puntos útiles.',
    'reports.upload': 'Subir foto o PDF',
    'reports.analyze': 'Analizar informe',
    'reports.analyzing': 'Analizando...',
    'reports.savedReports': 'Informes guardados',
  },
};

const RTL_LANGUAGES = new Set(['ks', 'sd', 'ur']);

const createTranslations = (overrides) => ({
  ...translations.en,
  ...overrides,
});

Object.assign(translations, {
  as: createTranslations({
    'nav.dashboard': 'ডেশ্বব’ৰ্ড',
    'nav.symptoms': 'লক্ষণ পৰীক্ষক',
    'nav.doctors': 'চিকিৎসক',
    'nav.emergency': 'জৰুৰীকালীন',
    'nav.healthTips': 'স্বাস্থ্য পৰামৰ্শ',
    'nav.reports': 'প্ৰতিবেদন',
    'nav.myService': 'মোৰ সেৱা',
    'nav.doctorDirectory': 'চিকিৎসক তালিকা',
    'nav.logout': 'লগ আউট',
    'profile.title': 'মোৰ প্ৰফাইল',
    'profile.subtitle': 'আপোনাৰ ব্যক্তিগত আৰু চিকিৎসা তথ্য পৰিচালনা কৰক',
    'profile.edit': 'সম্পাদনা',
    'profile.save': 'সাঁচক',
    'profile.saving': 'সাঁচি আছে...',
    'profile.info': 'প্ৰফাইল তথ্য',
    'profile.history': 'ইতিহাস',
    'profile.language': 'ভাষা',
    'profile.languageHelp': 'এপত ব্যৱহাৰ হ’বলগীয়া ভাষা বাছক।',
    'profile.fullName': 'সম্পূৰ্ণ নাম',
    'profile.email': 'ইমেইল',
    'profile.phone': 'ফোন নম্বৰ',
    'profile.age': 'বয়স',
    'profile.gender': 'লিংগ',
    'profile.bloodGroup': 'ৰক্ত গোট',
    'profile.emergencyContact': 'জৰুৰীকালীন যোগাযোগ',
    'profile.patientProfile': 'ৰোগীৰ প্ৰফাইল',
    'profile.doctorProfile': 'চিকিৎসকৰ প্ৰফাইল',
    'symptoms.title': 'লক্ষণ লিখক বা বাছক',
    'symptoms.analyze': 'লক্ষণ বিশ্লেষণ কৰক',
    'symptoms.clear': 'মচক',
    'reports.title': 'প্ৰতিবেদন বিশ্লেষণ',
    'reports.analyze': 'প্ৰতিবেদন বিশ্লেষণ কৰক',
  }),
  bn: createTranslations({
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.symptoms': 'উপসর্গ পরীক্ষক',
    'nav.doctors': 'ডাক্তার',
    'nav.emergency': 'জরুরি',
    'nav.healthTips': 'স্বাস্থ্য পরামর্শ',
    'nav.reports': 'রিপোর্ট',
    'nav.myService': 'আমার সেবা',
    'nav.doctorDirectory': 'ডাক্তার তালিকা',
    'nav.logout': 'লগ আউট',
    'profile.title': 'আমার প্রোফাইল',
    'profile.subtitle': 'আপনার ব্যক্তিগত ও চিকিৎসা তথ্য পরিচালনা করুন',
    'profile.edit': 'সম্পাদনা',
    'profile.save': 'সংরক্ষণ করুন',
    'profile.saving': 'সংরক্ষণ হচ্ছে...',
    'profile.info': 'প্রোফাইল তথ্য',
    'profile.history': 'ইতিহাস',
    'profile.language': 'ভাষা',
    'profile.languageHelp': 'অ্যাপে ব্যবহারের ভাষা বেছে নিন।',
    'profile.fullName': 'পুরো নাম',
    'profile.email': 'ইমেইল',
    'profile.phone': 'ফোন নম্বর',
    'profile.age': 'বয়স',
    'profile.gender': 'লিঙ্গ',
    'profile.bloodGroup': 'রক্তের গ্রুপ',
    'profile.emergencyContact': 'জরুরি যোগাযোগ',
    'profile.occupation': 'পেশা',
    'profile.address': 'ঠিকানা',
    'profile.patientProfile': 'রোগীর প্রোফাইল',
    'profile.doctorProfile': 'ডাক্তারের প্রোফাইল',
    'symptoms.title': 'উপসর্গ লিখুন বা নির্বাচন করুন',
    'symptoms.analyze': 'উপসর্গ বিশ্লেষণ করুন',
    'symptoms.clear': 'মুছুন',
    'reports.title': 'রিপোর্ট বিশ্লেষণ',
    'reports.analyze': 'রিপোর্ট বিশ্লেষণ করুন',
  }),
  brx: createTranslations({
    'nav.dashboard': 'डेशबोर्ड',
    'nav.symptoms': 'लक्षण नायबिजिरग्रा',
    'nav.doctors': 'डाक्तार',
    'nav.emergency': 'जरुरी',
    'nav.healthTips': 'सावस्रि सोलोंथाइ',
    'nav.reports': 'रिपोर्ट',
    'nav.myService': 'आंनि सिबिथाय',
    'nav.doctorDirectory': 'डाक्तार फारिलाइ',
    'nav.logout': 'लग आउट',
    'profile.title': 'आंनि प्रोफाइल',
    'profile.subtitle': 'नोंथांनि निजि आरो सावस्रि फोरमायथिहोग्राखौ सामलाय',
    'profile.edit': 'सुजु',
    'profile.save': 'सेभ खालाम',
    'profile.saving': 'सेभ खालामगासिनो...',
    'profile.language': 'राव',
    'profile.languageHelp': 'एपआव बाहायनो राव सायख।',
    'profile.fullName': 'आबुं मुं',
    'profile.email': 'इमेल',
    'profile.phone': 'फोन नाम्बार',
    'profile.age': 'बोसो',
    'profile.gender': 'लिंगी',
    'profile.bloodGroup': 'ब्लड ग्रुप',
    'profile.emergencyContact': 'जरुरी जगाजग',
    'symptoms.title': 'लक्षण लिर एबा सायख',
    'symptoms.analyze': 'लक्षण बिजिर',
    'reports.title': 'रिपोर्ट बिजिर',
  }),
  doi: createTranslations({
    'nav.dashboard': 'डैशबोर्ड',
    'nav.symptoms': 'लक्षण जांच',
    'nav.doctors': 'डाक्टर',
    'nav.emergency': 'आपातकाल',
    'nav.healthTips': 'सेहत सलाह',
    'nav.reports': 'रिपोर्टां',
    'nav.myService': 'मेरी सेवा',
    'nav.doctorDirectory': 'डाक्टर सूची',
    'nav.logout': 'लॉग आउट',
    'profile.title': 'मेरी प्रोफाइल',
    'profile.subtitle': 'अपनी निजी ते मेडिकल जानकारी संभालो',
    'profile.edit': 'संपादित करो',
    'profile.save': 'सेव करो',
    'profile.saving': 'सेव होआ करदा...',
    'profile.language': 'भाषा',
    'profile.languageHelp': 'ऐप च इस्तेमाल होन आली भाषा चुनो।',
    'profile.fullName': 'पूरा नां',
    'profile.email': 'ईमेल',
    'profile.phone': 'फोन नंबर',
    'profile.age': 'उमर',
    'profile.gender': 'लिंग',
    'profile.bloodGroup': 'ब्लड ग्रुप',
    'profile.emergencyContact': 'आपातकालीन संपर्क',
    'symptoms.title': 'लक्षण लिखो जां चुनो',
    'symptoms.analyze': 'लक्षण विश्लेषण करो',
    'reports.title': 'रिपोर्ट विश्लेषण',
  }),
  gu: createTranslations({
    'nav.dashboard': 'ડેશબોર્ડ',
    'nav.symptoms': 'લક્ષણ તપાસક',
    'nav.doctors': 'ડૉક્ટર્સ',
    'nav.emergency': 'આપાતકાલીન',
    'nav.healthTips': 'આરોગ્ય સલાહ',
    'nav.reports': 'રિપોર્ટ્સ',
    'nav.myService': 'મારી સેવા',
    'nav.doctorDirectory': 'ડૉક્ટર સૂચિ',
    'nav.logout': 'લૉગ આઉટ',
    'profile.title': 'મારી પ્રોફાઇલ',
    'profile.subtitle': 'તમારી વ્યક્તિગત અને તબીબી માહિતી સંચાલિત કરો',
    'profile.edit': 'સંપાદિત કરો',
    'profile.save': 'ફેરફારો સાચવો',
    'profile.saving': 'સાચવી રહ્યું છે...',
    'profile.info': 'પ્રોફાઇલ માહિતી',
    'profile.history': 'ઇતિહાસ',
    'profile.language': 'ભાષા',
    'profile.languageHelp': 'એપમાં ઉપયોગ થતી ભાષા પસંદ કરો.',
    'profile.fullName': 'પૂરું નામ',
    'profile.email': 'ઈમેલ',
    'profile.phone': 'ફોન નંબર',
    'profile.age': 'ઉંમર',
    'profile.gender': 'લિંગ',
    'profile.bloodGroup': 'બ્લડ ગ્રુપ',
    'profile.emergencyContact': 'આપાતકાલીન સંપર્ક',
    'profile.occupation': 'વ્યવસાય',
    'profile.address': 'સરનામું',
    'profile.patientProfile': 'દર્દી પ્રોફાઇલ',
    'profile.doctorProfile': 'ડૉક્ટર પ્રોફાઇલ',
    'symptoms.title': 'લક્ષણો લખો અથવા પસંદ કરો',
    'symptoms.analyze': 'લક્ષણોનું વિશ્લેષણ કરો',
    'symptoms.clear': 'સાફ કરો',
    'reports.title': 'રિપોર્ટ વિશ્લેષણ',
    'reports.analyze': 'રિપોર્ટનું વિશ્લેષણ કરો',
  }),
  kn: createTranslations({
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.symptoms': 'ಲಕ್ಷಣ ಪರಿಶೀಲಕ',
    'nav.doctors': 'ವೈದ್ಯರು',
    'nav.emergency': 'ತುರ್ತು',
    'nav.healthTips': 'ಆರೋಗ್ಯ ಸಲಹೆಗಳು',
    'nav.reports': 'ವರದಿಗಳು',
    'nav.myService': 'ನನ್ನ ಸೇವೆ',
    'nav.doctorDirectory': 'ವೈದ್ಯರ ಪಟ್ಟಿ',
    'nav.logout': 'ಲಾಗ್ ಔಟ್',
    'profile.title': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    'profile.subtitle': 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಮತ್ತು ವೈದ್ಯಕೀಯ ಮಾಹಿತಿಯನ್ನು ನಿರ್ವಹಿಸಿ',
    'profile.edit': 'ಸಂಪಾದಿಸಿ',
    'profile.save': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    'profile.saving': 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
    'profile.info': 'ಪ್ರೊಫೈಲ್ ಮಾಹಿತಿ',
    'profile.history': 'ಇತಿಹಾಸ',
    'profile.language': 'ಭಾಷೆ',
    'profile.languageHelp': 'ಅಪ್ಲಿಕೇಶನ್‌ನಲ್ಲಿ ಬಳಸುವ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    'profile.fullName': 'ಪೂರ್ಣ ಹೆಸರು',
    'profile.email': 'ಇಮೇಲ್',
    'profile.phone': 'ಫೋನ್ ಸಂಖ್ಯೆ',
    'profile.age': 'ವಯಸ್ಸು',
    'profile.gender': 'ಲಿಂಗ',
    'profile.bloodGroup': 'ರಕ್ತದ ಗುಂಪು',
    'profile.emergencyContact': 'ತುರ್ತು ಸಂಪರ್ಕ',
    'profile.occupation': 'ಉದ್ಯೋಗ',
    'profile.address': 'ವಿಳಾಸ',
    'profile.patientProfile': 'ರೋಗಿಯ ಪ್ರೊಫೈಲ್',
    'profile.doctorProfile': 'ವೈದ್ಯರ ಪ್ರೊಫೈಲ್',
    'symptoms.title': 'ಲಕ್ಷಣಗಳನ್ನು ಬರೆಯಿರಿ ಅಥವಾ ಆಯ್ಕೆಮಾಡಿ',
    'symptoms.analyze': 'ಲಕ್ಷಣಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ',
    'symptoms.clear': 'ತೆರವುಗೊಳಿಸಿ',
    'reports.title': 'ವರದಿ ವಿಶ್ಲೇಷಣೆ',
    'reports.analyze': 'ವರದಿಯನ್ನು ವಿಶ್ಲೇಷಿಸಿ',
  }),
  ks: createTranslations({
    'nav.dashboard': 'ڈیش بورڈ',
    'nav.symptoms': 'علامت چیکر',
    'nav.doctors': 'ڈاکٹر',
    'nav.emergency': 'ہنگامی',
    'nav.healthTips': 'صحت مشورے',
    'nav.reports': 'رپورٹس',
    'nav.myService': 'میٛون خدمت',
    'nav.doctorDirectory': 'ڈاکٹر فہرست',
    'nav.logout': 'لاگ آؤٹ',
    'profile.title': 'میٛون پروفائل',
    'profile.subtitle': 'پنُن ذاتی تہ طبی معلومات سنبھالیو',
    'profile.edit': 'ترمیم',
    'profile.save': 'محفوظ کرو',
    'profile.saving': 'محفوظ کران...',
    'profile.language': 'زبان',
    'profile.languageHelp': 'ایپس منز استعمال زبان منتخب کریو۔',
    'profile.fullName': 'پورا ناو',
    'profile.email': 'ای میل',
    'profile.phone': 'فون نمبر',
    'profile.age': 'عمر',
    'profile.gender': 'جنس',
    'profile.bloodGroup': 'بلڈ گروپ',
    'profile.emergencyContact': 'ہنگامی رابطہ',
    'symptoms.title': 'علامات لکھیو یا منتخب کریو',
    'symptoms.analyze': 'علامات تجزیہ کریو',
    'reports.title': 'رپورٹ تجزیہ',
  }),
  kok: createTranslations({
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.symptoms': 'लक्षण तपासणी',
    'nav.doctors': 'दोतोर',
    'nav.emergency': 'आपत्कालीन',
    'nav.healthTips': 'भलायकी सल्ले',
    'nav.reports': 'अहवाल',
    'nav.myService': 'म्हजी सेवा',
    'nav.doctorDirectory': 'दोतोर यादी',
    'nav.logout': 'लॉग आऊट',
    'profile.title': 'म्हजो प्रोफाइल',
    'profile.subtitle': 'तुमची वैयक्तिक आनी वैद्यकीय माहिती सांभाळात',
    'profile.edit': 'संपादित करात',
    'profile.save': 'जतन करात',
    'profile.saving': 'जतन जाता...',
    'profile.language': 'भास',
    'profile.languageHelp': 'अॅपांत वापरपाची भास निवडात.',
    'profile.fullName': 'पुराय नाव',
    'profile.email': 'ईमेल',
    'profile.phone': 'फोन नंबर',
    'profile.age': 'वय',
    'profile.gender': 'लिंग',
    'profile.bloodGroup': 'रक्त गट',
    'profile.emergencyContact': 'आपत्कालीन संपर्क',
    'symptoms.title': 'लक्षणां बरयात वा निवडात',
    'symptoms.analyze': 'लक्षणांचें विश्लेषण करात',
    'reports.title': 'अहवाल विश्लेषण',
  }),
  mai: createTranslations({
    'nav.dashboard': 'डैशबोर्ड',
    'nav.symptoms': 'लक्षण जांच',
    'nav.doctors': 'डाक्टर',
    'nav.emergency': 'आपातकाल',
    'nav.healthTips': 'स्वास्थ्य सलाह',
    'nav.reports': 'रिपोर्ट',
    'nav.myService': 'हमर सेवा',
    'nav.doctorDirectory': 'डाक्टर सूची',
    'nav.logout': 'लॉग आउट',
    'profile.title': 'हमर प्रोफाइल',
    'profile.subtitle': 'अपन व्यक्तिगत आ चिकित्सा जानकारी प्रबंधित करू',
    'profile.edit': 'संपादित करू',
    'profile.save': 'सेव करू',
    'profile.saving': 'सेव भऽ रहल अछि...',
    'profile.language': 'भाषा',
    'profile.languageHelp': 'ऐप मे उपयोग होए वाली भाषा चुनू।',
    'profile.fullName': 'पूरा नाम',
    'profile.email': 'ईमेल',
    'profile.phone': 'फोन नंबर',
    'profile.age': 'उम्र',
    'profile.gender': 'लिंग',
    'profile.bloodGroup': 'ब्लड ग्रुप',
    'profile.emergencyContact': 'आपातकालीन संपर्क',
    'symptoms.title': 'लक्षण लिखू वा चुनू',
    'symptoms.analyze': 'लक्षण विश्लेषण करू',
    'reports.title': 'रिपोर्ट विश्लेषण',
  }),
  ml: createTranslations({
    'nav.dashboard': 'ഡാഷ്ബോർഡ്',
    'nav.symptoms': 'ലക്ഷണ പരിശോധന',
    'nav.doctors': 'ഡോക്ടർമാർ',
    'nav.emergency': 'അടിയന്തിരം',
    'nav.healthTips': 'ആരോഗ്യ നിർദേശങ്ങൾ',
    'nav.reports': 'റിപ്പോർട്ടുകൾ',
    'nav.myService': 'എന്റെ സേവനം',
    'nav.doctorDirectory': 'ഡോക്ടർ പട്ടിക',
    'nav.logout': 'ലോഗ് ഔട്ട്',
    'profile.title': 'എന്റെ പ്രൊഫൈൽ',
    'profile.subtitle': 'നിങ്ങളുടെ വ്യക്തിഗതവും മെഡിക്കൽ വിവരങ്ങളും നിയന്ത്രിക്കുക',
    'profile.edit': 'തിരുത്തുക',
    'profile.save': 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
    'profile.saving': 'സംരക്ഷിക്കുന്നു...',
    'profile.info': 'പ്രൊഫൈൽ വിവരം',
    'profile.history': 'ചരിത്രം',
    'profile.language': 'ഭാഷ',
    'profile.languageHelp': 'ആപ്പിൽ ഉപയോഗിക്കുന്ന ഭാഷ തിരഞ്ഞെടുക്കുക.',
    'profile.fullName': 'പൂർണ്ണ പേര്',
    'profile.email': 'ഇമെയിൽ',
    'profile.phone': 'ഫോൺ നമ്പർ',
    'profile.age': 'പ്രായം',
    'profile.gender': 'ലിംഗം',
    'profile.bloodGroup': 'രക്തഗ്രൂപ്പ്',
    'profile.emergencyContact': 'അടിയന്തിര ബന്ധപ്പെടൽ',
    'profile.occupation': 'തൊഴിൽ',
    'profile.address': 'വിലാസം',
    'profile.patientProfile': 'രോഗിയുടെ പ്രൊഫൈൽ',
    'profile.doctorProfile': 'ഡോക്ടറുടെ പ്രൊഫൈൽ',
    'symptoms.title': 'ലക്ഷണങ്ങൾ എഴുതുക അല്ലെങ്കിൽ തിരഞ്ഞെടുക്കുക',
    'symptoms.analyze': 'ലക്ഷണങ്ങൾ വിശകലനം ചെയ്യുക',
    'symptoms.clear': 'മായ്ക്കുക',
    'reports.title': 'റിപ്പോർട്ട് വിശകലനം',
    'reports.analyze': 'റിപ്പോർട്ട് വിശകലനം ചെയ്യുക',
  }),
  mni: createTranslations({
    'nav.dashboard': 'ꯗꯦꯁꯕꯣꯔꯗ',
    'nav.symptoms': 'ꯂꯥꯏꯅꯥ ꯌꯦꯡꯕ',
    'nav.doctors': 'ꯗꯣꯛꯇꯔ',
    'nav.emergency': 'ꯑꯊꯨꯕ',
    'nav.healthTips': 'ꯍꯦꯜꯊ ꯇꯤꯞꯁ',
    'nav.reports': 'ꯔꯤꯄꯣꯔꯠ',
    'nav.myService': 'ꯑꯩꯒꯤ ꯁꯔꯚꯤꯁ',
    'nav.doctorDirectory': 'ꯗꯣꯛꯇꯔ ꯂꯤꯁ꯭ꯠ',
    'nav.logout': 'ꯂꯣꯒ ꯑꯥꯎꯠ',
    'profile.title': 'ꯑꯩꯒꯤ ꯄ꯭ꯔꯣꯐꯥꯏꯜ',
    'profile.edit': 'ꯁꯦꯝꯗꯣꯛꯄ',
    'profile.save': 'ꯁꯦꯚ ꯇꯧꯕ',
    'profile.saving': 'ꯁꯦꯚ ꯇꯧꯔꯤ...',
    'profile.language': 'ꯂꯣꯜ',
    'profile.languageHelp': 'ꯑꯦꯞꯇ ꯁꯤꯖꯤꯟꯅꯕ ꯂꯣꯜ ꯈꯟꯕꯤꯌꯨ।',
    'profile.fullName': 'ꯃꯄꯨꯡ ꯐꯥꯕ ꯃꯃꯤꯡ',
    'profile.email': 'ꯏꯃꯦꯜ',
    'profile.phone': 'ꯐꯣꯟ ꯅꯝꯕꯔ',
    'profile.age': 'ꯆꯍꯤ',
    'symptoms.title': 'ꯂꯥꯏꯅꯥ ꯏꯕꯤꯌꯨ ꯅꯠꯇ꯭ꯔꯒ ꯈꯟꯕꯤꯌꯨ',
    'reports.title': 'ꯔꯤꯄꯣꯔꯠ ꯑꯦꯅꯥꯂꯥꯏꯁꯤꯁ',
  }),
  mr: createTranslations({
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.symptoms': 'लक्षण तपासक',
    'nav.doctors': 'डॉक्टर',
    'nav.emergency': 'आपत्कालीन',
    'nav.healthTips': 'आरोग्य सल्ले',
    'nav.reports': 'अहवाल',
    'nav.myService': 'माझी सेवा',
    'nav.doctorDirectory': 'डॉक्टर यादी',
    'nav.logout': 'लॉग आउट',
    'profile.title': 'माझी प्रोफाइल',
    'profile.subtitle': 'तुमची वैयक्तिक आणि वैद्यकीय माहिती व्यवस्थापित करा',
    'profile.edit': 'संपादित करा',
    'profile.save': 'बदल जतन करा',
    'profile.saving': 'जतन होत आहे...',
    'profile.info': 'प्रोफाइल माहिती',
    'profile.history': 'इतिहास',
    'profile.language': 'भाषा',
    'profile.languageHelp': 'अॅपमध्ये वापरली जाणारी भाषा निवडा.',
    'profile.fullName': 'पूर्ण नाव',
    'profile.email': 'ईमेल',
    'profile.phone': 'फोन नंबर',
    'profile.age': 'वय',
    'profile.gender': 'लिंग',
    'profile.bloodGroup': 'रक्तगट',
    'profile.emergencyContact': 'आपत्कालीन संपर्क',
    'profile.occupation': 'व्यवसाय',
    'profile.address': 'पत्ता',
    'profile.patientProfile': 'रुग्ण प्रोफाइल',
    'profile.doctorProfile': 'डॉक्टर प्रोफाइल',
    'symptoms.title': 'लक्षणे लिहा किंवा निवडा',
    'symptoms.analyze': 'लक्षणांचे विश्लेषण करा',
    'symptoms.clear': 'साफ करा',
    'reports.title': 'अहवाल विश्लेषण',
    'reports.analyze': 'अहवालाचे विश्लेषण करा',
  }),
  ne: createTranslations({
    'nav.dashboard': 'ड्यासबोर्ड',
    'nav.symptoms': 'लक्षण जाँच',
    'nav.doctors': 'डाक्टरहरू',
    'nav.emergency': 'आपतकालीन',
    'nav.healthTips': 'स्वास्थ्य सुझाव',
    'nav.reports': 'रिपोर्टहरू',
    'nav.myService': 'मेरो सेवा',
    'nav.doctorDirectory': 'डाक्टर सूची',
    'nav.logout': 'लग आउट',
    'profile.title': 'मेरो प्रोफाइल',
    'profile.subtitle': 'आफ्नो व्यक्तिगत र चिकित्सा जानकारी व्यवस्थापन गर्नुहोस्',
    'profile.edit': 'सम्पादन',
    'profile.save': 'परिवर्तन सुरक्षित गर्नुहोस्',
    'profile.saving': 'सुरक्षित हुँदैछ...',
    'profile.language': 'भाषा',
    'profile.languageHelp': 'एपमा प्रयोग हुने भाषा छान्नुहोस्।',
    'profile.fullName': 'पूरा नाम',
    'profile.email': 'इमेल',
    'profile.phone': 'फोन नम्बर',
    'profile.age': 'उमेर',
    'profile.gender': 'लिङ्ग',
    'profile.bloodGroup': 'रक्त समूह',
    'profile.emergencyContact': 'आपतकालीन सम्पर्क',
    'symptoms.title': 'लक्षण लेख्नुहोस् वा छान्नुहोस्',
    'symptoms.analyze': 'लक्षण विश्लेषण गर्नुहोस्',
    'reports.title': 'रिपोर्ट विश्लेषण',
  }),
  or: createTranslations({
    'nav.dashboard': 'ଡ୍ୟାଶବୋର୍ଡ',
    'nav.symptoms': 'ଲକ୍ଷଣ ପରୀକ୍ଷକ',
    'nav.doctors': 'ଡାକ୍ତର',
    'nav.emergency': 'ଜରୁରୀକାଳୀନ',
    'nav.healthTips': 'ସ୍ୱାସ୍ଥ୍ୟ ପରାମର୍ଶ',
    'nav.reports': 'ରିପୋର୍ଟ',
    'nav.myService': 'ମୋ ସେବା',
    'nav.doctorDirectory': 'ଡାକ୍ତର ତାଲିକା',
    'nav.logout': 'ଲଗ୍ ଆଉଟ୍',
    'profile.title': 'ମୋ ପ୍ରୋଫାଇଲ୍',
    'profile.subtitle': 'ଆପଣଙ୍କ ବ୍ୟକ୍ତିଗତ ଏବଂ ଚିକିତ୍ସା ସୂଚନା ପରିଚାଳନା କରନ୍ତୁ',
    'profile.edit': 'ସମ୍ପାଦନା',
    'profile.save': 'ପରିବର୍ତ୍ତନ ସଞ୍ଚୟ',
    'profile.saving': 'ସଞ୍ଚୟ ହେଉଛି...',
    'profile.info': 'ପ୍ରୋଫାଇଲ୍ ସୂଚନା',
    'profile.history': 'ଇତିହାସ',
    'profile.language': 'ଭାଷା',
    'profile.languageHelp': 'ଆପ୍‌ରେ ବ୍ୟବହୃତ ଭାଷା ବାଛନ୍ତୁ।',
    'profile.fullName': 'ପୂର୍ଣ୍ଣ ନାମ',
    'profile.email': 'ଇମେଲ୍',
    'profile.phone': 'ଫୋନ୍ ନମ୍ବର',
    'profile.age': 'ବୟସ',
    'profile.gender': 'ଲିଙ୍ଗ',
    'profile.bloodGroup': 'ରକ୍ତ ଗୋଷ୍ଠୀ',
    'profile.emergencyContact': 'ଜରୁରୀ ସମ୍ପର୍କ',
    'profile.occupation': 'ପେଶା',
    'profile.address': 'ଠିକଣା',
    'profile.patientProfile': 'ରୋଗୀ ପ୍ରୋଫାଇଲ୍',
    'profile.doctorProfile': 'ଡାକ୍ତର ପ୍ରୋଫାଇଲ୍',
    'symptoms.title': 'ଲକ୍ଷଣ ଲେଖନ୍ତୁ କିମ୍ବା ବାଛନ୍ତୁ',
    'symptoms.analyze': 'ଲକ୍ଷଣ ବିଶ୍ଳେଷଣ',
    'symptoms.clear': 'ସଫା କରନ୍ତୁ',
    'reports.title': 'ରିପୋର୍ଟ ବିଶ୍ଳେଷଣ',
    'reports.analyze': 'ରିପୋର୍ଟ ବିଶ୍ଳେଷଣ',
  }),
  pa: createTranslations({
    'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'nav.symptoms': 'ਲੱਛਣ ਜਾਂਚਕ',
    'nav.doctors': 'ਡਾਕਟਰ',
    'nav.emergency': 'ਐਮਰਜੈਂਸੀ',
    'nav.healthTips': 'ਸਿਹਤ ਸੁਝਾਅ',
    'nav.reports': 'ਰਿਪੋਰਟਾਂ',
    'nav.myService': 'ਮੇਰੀ ਸੇਵਾ',
    'nav.doctorDirectory': 'ਡਾਕਟਰ ਸੂਚੀ',
    'nav.logout': 'ਲੌਗ ਆਉਟ',
    'profile.title': 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
    'profile.subtitle': 'ਆਪਣੀ ਨਿੱਜੀ ਅਤੇ ਮੈਡੀਕਲ ਜਾਣਕਾਰੀ ਸੰਭਾਲੋ',
    'profile.edit': 'ਸੋਧੋ',
    'profile.save': 'ਬਦਲਾਅ ਸੰਭਾਲੋ',
    'profile.saving': 'ਸੰਭਾਲਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
    'profile.info': 'ਪ੍ਰੋਫਾਈਲ ਜਾਣਕਾਰੀ',
    'profile.history': 'ਇਤਿਹਾਸ',
    'profile.language': 'ਭਾਸ਼ਾ',
    'profile.languageHelp': 'ਐਪ ਵਿੱਚ ਵਰਤੀ ਜਾਣ ਵਾਲੀ ਭਾਸ਼ਾ ਚੁਣੋ।',
    'profile.fullName': 'ਪੂਰਾ ਨਾਮ',
    'profile.email': 'ਈਮੇਲ',
    'profile.phone': 'ਫੋਨ ਨੰਬਰ',
    'profile.age': 'ਉਮਰ',
    'profile.gender': 'ਲਿੰਗ',
    'profile.bloodGroup': 'ਬਲੱਡ ਗਰੁੱਪ',
    'profile.emergencyContact': 'ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ',
    'profile.occupation': 'ਪੇਸ਼ਾ',
    'profile.address': 'ਪਤਾ',
    'profile.patientProfile': 'ਮਰੀਜ਼ ਪ੍ਰੋਫਾਈਲ',
    'profile.doctorProfile': 'ਡਾਕਟਰ ਪ੍ਰੋਫਾਈਲ',
    'symptoms.title': 'ਲੱਛਣ ਲਿਖੋ ਜਾਂ ਚੁਣੋ',
    'symptoms.analyze': 'ਲੱਛਣਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
    'symptoms.clear': 'ਸਾਫ਼ ਕਰੋ',
    'reports.title': 'ਰਿਪੋਰਟ ਵਿਸ਼ਲੇਸ਼ਣ',
    'reports.analyze': 'ਰਿਪੋਰਟ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
  }),
  sa: createTranslations({
    'nav.dashboard': 'डैशबोर्ड',
    'nav.symptoms': 'लक्षणपरीक्षकः',
    'nav.doctors': 'वैद्याः',
    'nav.emergency': 'आपत्कालः',
    'nav.healthTips': 'आरोग्यसूचनाः',
    'nav.reports': 'प्रतिवेदनानि',
    'nav.myService': 'मम सेवा',
    'nav.doctorDirectory': 'वैद्यसूची',
    'nav.logout': 'निर्गच्छतु',
    'profile.title': 'मम परिचयः',
    'profile.subtitle': 'स्वकीयां वैयक्तिकीं चिकित्सकीयां च सूचनां व्यवस्थापयतु',
    'profile.edit': 'सम्पादयतु',
    'profile.save': 'परिवर्तनानि रक्षतु',
    'profile.saving': 'रक्षति...',
    'profile.language': 'भाषा',
    'profile.languageHelp': 'अनुप्रयोगे प्रयुक्तां भाषां चिनोतु।',
    'profile.fullName': 'पूर्णं नाम',
    'profile.email': 'ईमेल',
    'profile.phone': 'दूरभाषाङ्कः',
    'profile.age': 'वयः',
    'profile.gender': 'लिङ्गम्',
    'profile.bloodGroup': 'रक्तसमूहः',
    'profile.emergencyContact': 'आपत्कालीनसम्पर्कः',
    'symptoms.title': 'लक्षणानि लिखतु अथवा चिनोतु',
    'symptoms.analyze': 'लक्षणविश्लेषणम्',
    'reports.title': 'प्रतिवेदनविश्लेषणम्',
  }),
  sat: createTranslations({
    'nav.dashboard': 'ᱰᱮᱥᱵᱚᱨᱰ',
    'nav.symptoms': 'ᱪᱤᱱᱦᱟ ᱧᱮᱞ',
    'nav.doctors': 'ᱰᱟᱠᱛᱟᱨ',
    'nav.emergency': 'ᱡᱚᱨᱩᱨᱤ',
    'nav.healthTips': 'ᱥᱟᱹᱜᱩᱱ ᱥᱟᱞᱟᱦ',
    'nav.reports': 'ᱨᱤᱯᱚᱨᱴ',
    'nav.myService': 'ᱤᱧᱟᱜ ᱥᱮᱵᱟ',
    'nav.doctorDirectory': 'ᱰᱟᱠᱛᱟᱨ ᱛᱟᱞᱤᱠᱟ',
    'nav.logout': 'ᱞᱚᱜ ᱟᱣᱩᱴ',
    'profile.title': 'ᱤᱧᱟᱜ ᱯᱨᱚᱯᱷᱟᱭᱤᱞ',
    'profile.edit': 'ᱥᱟᱯᱲᱟᱣ',
    'profile.save': 'ᱥᱟᱸᱪᱟᱣ',
    'profile.saving': 'ᱥᱟᱸᱪᱟᱣ ᱪᱟᱞᱟᱜ...',
    'profile.language': 'ᱯᱟᱹᱨᱥᱤ',
    'profile.languageHelp': 'ᱮᱯ ᱨᱮ ᱵᱮᱵᱷᱟᱨ ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱟᱣ ᱢᱮ।',
    'profile.fullName': 'ᱯᱩᱨᱟᱹ ᱧᱩᱛᱩᱢ',
    'profile.email': 'ᱤᱢᱮᱞ',
    'profile.phone': 'ᱯᱷᱚᱱ ᱱᱚᱢᱵᱚᱨ',
    'symptoms.title': 'ᱪᱤᱱᱦᱟ ᱚᱞ ᱢᱮ ᱟᱨ ᱵᱟᱪᱷᱟᱣ ᱢᱮ',
    'reports.title': 'ᱨᱤᱯᱚᱨᱴ ᱵᱤᱥᱞᱮᱥᱚᱱ',
  }),
  sd: createTranslations({
    'nav.dashboard': 'ڊيش بورڊ',
    'nav.symptoms': 'علامت چيڪر',
    'nav.doctors': 'ڊاڪٽر',
    'nav.emergency': 'ايمرجنسي',
    'nav.healthTips': 'صحت جون صلاحون',
    'nav.reports': 'رپورٽون',
    'nav.myService': 'منهنجي سروس',
    'nav.doctorDirectory': 'ڊاڪٽر لسٽ',
    'nav.logout': 'لاگ آئوٽ',
    'profile.title': 'منهنجو پروفائل',
    'profile.subtitle': 'پنهنجي ذاتي ۽ طبي معلومات سنڀاليو',
    'profile.edit': 'تبديل ڪريو',
    'profile.save': 'تبديليون محفوظ ڪريو',
    'profile.saving': 'محفوظ ٿي رهيو آهي...',
    'profile.language': 'ٻولي',
    'profile.languageHelp': 'ايپ ۾ استعمال ٿيندڙ ٻولي چونڊيو.',
    'profile.fullName': 'پورو نالو',
    'profile.email': 'اي ميل',
    'profile.phone': 'فون نمبر',
    'profile.age': 'عمر',
    'profile.gender': 'جنس',
    'profile.bloodGroup': 'بلڊ گروپ',
    'profile.emergencyContact': 'ايمرجنسي رابطو',
    'symptoms.title': 'علامتون لکو يا چونڊيو',
    'symptoms.analyze': 'علامتن جو تجزيو ڪريو',
    'reports.title': 'رپورٽ تجزيو',
  }),
  ta: createTranslations({
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.symptoms': 'அறிகுறி பரிசோதகர்',
    'nav.doctors': 'மருத்துவர்கள்',
    'nav.emergency': 'அவசரம்',
    'nav.healthTips': 'சுகாதார குறிப்புகள்',
    'nav.reports': 'அறிக்கைகள்',
    'nav.myService': 'என் சேவை',
    'nav.doctorDirectory': 'மருத்துவர் பட்டியல்',
    'nav.logout': 'வெளியேறு',
    'profile.title': 'என் சுயவிவரம்',
    'profile.subtitle': 'உங்கள் தனிப்பட்ட மற்றும் மருத்துவ தகவல்களை நிர்வகிக்கவும்',
    'profile.edit': 'திருத்து',
    'profile.save': 'மாற்றங்களைச் சேமி',
    'profile.saving': 'சேமிக்கப்படுகிறது...',
    'profile.info': 'சுயவிவர தகவல்',
    'profile.history': 'வரலாறு',
    'profile.language': 'மொழி',
    'profile.languageHelp': 'பயன்பாட்டில் பயன்படுத்தப்படும் மொழியைத் தேர்ந்தெடுக்கவும்.',
    'profile.fullName': 'முழு பெயர்',
    'profile.email': 'மின்னஞ்சல்',
    'profile.phone': 'தொலைபேசி எண்',
    'profile.age': 'வயது',
    'profile.gender': 'பாலினம்',
    'profile.bloodGroup': 'இரத்த வகை',
    'profile.emergencyContact': 'அவசர தொடர்பு',
    'profile.occupation': 'தொழில்',
    'profile.address': 'முகவரி',
    'profile.patientProfile': 'நோயாளர் சுயவிவரம்',
    'profile.doctorProfile': 'மருத்துவர் சுயவிவரம்',
    'symptoms.title': 'அறிகுறிகளை எழுதவும் அல்லது தேர்ந்தெடுக்கவும்',
    'symptoms.analyze': 'அறிகுறிகளை பகுப்பாய்வு செய்',
    'symptoms.clear': 'அழி',
    'reports.title': 'அறிக்கை பகுப்பாய்வு',
    'reports.analyze': 'அறிக்கையை பகுப்பாய்வு செய்',
  }),
  te: createTranslations({
    'nav.dashboard': 'డ్యాష్‌బోర్డ్',
    'nav.symptoms': 'లక్షణాల పరిశీలకుడు',
    'nav.doctors': 'వైద్యులు',
    'nav.emergency': 'అత్యవసరం',
    'nav.healthTips': 'ఆరోగ్య సూచనలు',
    'nav.reports': 'రిపోర్టులు',
    'nav.myService': 'నా సేవ',
    'nav.doctorDirectory': 'వైద్యుల జాబితా',
    'nav.logout': 'లాగ్ అవుట్',
    'profile.title': 'నా ప్రొఫైల్',
    'profile.subtitle': 'మీ వ్యక్తిగత మరియు వైద్య సమాచారాన్ని నిర్వహించండి',
    'profile.edit': 'సవరించు',
    'profile.save': 'మార్పులను సేవ్ చేయి',
    'profile.saving': 'సేవ్ అవుతోంది...',
    'profile.info': 'ప్రొఫైల్ సమాచారం',
    'profile.history': 'చరిత్ర',
    'profile.language': 'భాష',
    'profile.languageHelp': 'యాప్‌లో ఉపయోగించే భాషను ఎంచుకోండి.',
    'profile.fullName': 'పూర్తి పేరు',
    'profile.email': 'ఇమెయిల్',
    'profile.phone': 'ఫోన్ నంబర్',
    'profile.age': 'వయస్సు',
    'profile.gender': 'లింగం',
    'profile.bloodGroup': 'రక్త గ్రూప్',
    'profile.emergencyContact': 'అత్యవసర సంప్రదింపు',
    'profile.occupation': 'వృత్తి',
    'profile.address': 'చిరునామా',
    'profile.patientProfile': 'రోగి ప్రొఫైల్',
    'profile.doctorProfile': 'వైద్యుడి ప్రొఫైల్',
    'symptoms.title': 'లక్షణాలను వ్రాయండి లేదా ఎంచుకోండి',
    'symptoms.analyze': 'లక్షణాలను విశ్లేషించు',
    'symptoms.clear': 'తొలగించు',
    'reports.title': 'రిపోర్ట్ విశ్లేషణ',
    'reports.analyze': 'రిపోర్టును విశ్లేషించు',
  }),
  ur: createTranslations({
    'nav.dashboard': 'ڈیش بورڈ',
    'nav.symptoms': 'علامات چیکر',
    'nav.doctors': 'ڈاکٹرز',
    'nav.emergency': 'ایمرجنسی',
    'nav.healthTips': 'صحت کے مشورے',
    'nav.reports': 'رپورٹس',
    'nav.myService': 'میری سروس',
    'nav.doctorDirectory': 'ڈاکٹر فہرست',
    'nav.logout': 'لاگ آؤٹ',
    'profile.title': 'میری پروفائل',
    'profile.subtitle': 'اپنی ذاتی اور طبی معلومات کا انتظام کریں',
    'profile.edit': 'ترمیم کریں',
    'profile.save': 'تبدیلیاں محفوظ کریں',
    'profile.saving': 'محفوظ کیا جا رہا ہے...',
    'profile.info': 'پروفائل معلومات',
    'profile.history': 'تاریخ',
    'profile.language': 'زبان',
    'profile.languageHelp': 'ایپ میں استعمال ہونے والی زبان منتخب کریں۔',
    'profile.fullName': 'پورا نام',
    'profile.email': 'ای میل',
    'profile.phone': 'فون نمبر',
    'profile.age': 'عمر',
    'profile.gender': 'جنس',
    'profile.bloodGroup': 'بلڈ گروپ',
    'profile.emergencyContact': 'ایمرجنسی رابطہ',
    'profile.occupation': 'پیشہ',
    'profile.address': 'پتہ',
    'profile.patientProfile': 'مریض پروفائل',
    'profile.doctorProfile': 'ڈاکٹر پروفائل',
    'symptoms.title': 'علامات لکھیں یا منتخب کریں',
    'symptoms.analyze': 'علامات کا تجزیہ کریں',
    'symptoms.clear': 'صاف کریں',
    'reports.title': 'رپورٹ تجزیہ',
    'reports.analyze': 'رپورٹ کا تجزیہ کریں',
  }),
});

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => localStorage.getItem('language') || 'en');

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = RTL_LANGUAGES.has(language) ? 'rtl' : 'ltr';
  }, [language]);

  const value = useMemo(() => ({
    language,
    languages: LANGUAGES,
    setLanguage: setLanguageState,
    t: (key) => translations[language]?.[key] || translations.en[key] || key,
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
